apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - name: 80-80
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30088
  type: NodePort
  selector:
    app: nginx
